Refactor CI/CD (#379)
* Refactor CI/CD workflow

* Use `actions/cache` to cache dependencies

* Add restore-keys to reuse cache across versions

* Use fixed cache key with cargo-cache clean-unref

* Use clean build for release

* Move cargo clean to after all builds

* Fix binary naming

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,7 +3,7 @@ name: Build and Release
 on:
   workflow_dispatch:
   push:
-    branches: [main]
+    branches: "*"
     tags:
       - "v*.*.*"
 
@@ -20,7 +20,13 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
+
+      - name: Install libudev-dev on Ubuntu
+        if: runner.os == 'Ubuntu'
+        run: |
+          sudo apt-get update
+          sudo apt-get install libudev-dev
 
       - name: Install Latest Rust
         uses: actions-rs/toolchain@v1
@@ -29,28 +35,77 @@ jobs:
           default: true
           override: true
 
+      - name: Install rustfmt, clippy and cargo-cache
+        run: |
+          rustup component add rustfmt clippy
+          cargo install cargo-cache
+
+      - name: Cache Dependencies
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+            target/
+          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-cargo-
+
       - name: Build
         id: build
         shell: bash
         run: |
           binary_extension=""
-          if [[ "${RUNNER_OS}" == "Linux" ]]; then
-            echo "Installing libudev-dev"
-            sudo apt-get update
-            sudo apt-get install libudev-dev
-            binary_path="sugar-ubuntu-latest"
-          fi
           if [[ "${RUNNER_OS}" == "Windows" ]]; then
             binary_extension=".exe"
-            binary_path="sugar-${{ matrix.os }}${binary_extension}"
-          fi
-          if [[ "${RUNNER_OS}" == "macOS" ]]; then
+            binary_path="sugar-windows-latest${binary_extension}"
+          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
             binary_path="sugar-macos-intel-latest"
+          elif [[ "${RUNNER_OS}" == "Ubuntu" ]]; then
+            binary_path="sugar-ubuntu-latest"
+          else
+            echo "error: unknown OS: ${RUNNER_OS}"
+            exit 1
           fi
-          cargo build --all --release --locked
-          mv "target/release/sugar${binary_extension}" "${binary_path}"
           echo "::set-output name=binary_path::${binary_path}"
+
+          # clean build for release
+          if [[ "${GITHUB_REF}" = refs/tags/* ]]; then
+            cargo clean
+          fi
+
+          cargo build --all --release --locked
+          cp "target/release/sugar${binary_extension}" "${binary_path}"
           strip "${binary_path}"
+
+      - name: Test
+        uses: actions-rs/cargo@v1
+        with:
+          command: test
+
+      - name: Rustfmt
+        uses: actions-rs/cargo@v1
+        with:
+          command: fmt
+          args: --all -- --check
+
+      - name: Clippy
+        uses: actions-rs/cargo@v1
+        with:
+          command: clippy
+          args: -- -D warnings
+
+      - name: Cleanup Dependencies
+        run: cargo cache clean-unref
+
+      - name: Publish Artifacts
+        uses: actions/upload-artifact@v3
+        if: "!startsWith(github.ref, 'refs/tags/')"
+        with:
+          name: ${{ matrix.os }}
+          path: ${{ steps.build.outputs.binary_path }}
 
       - name: Release Tags
         uses: softprops/action-gh-release@v1
